### ISSUE TITLE
Database Seeding

### ISSUE THREAD

**Issue by Houbsi** [eramitgupta/laravel-role-permission#5]
I was a bit stunned while using the permissions, which are seeded with the package.

It should be always the same direction and follow the same rule like:

`{{model}}-{{action}}`

Like this it follows more the convention of first the model and then the action.

## Status

```php
$roles = [
            'admin' => ['create-post', 'post-edit', 'post-delete', 'post-update'],
            'user' => ['create-user', 'user-edit', 'user-delete', 'user-update'],
        ];
```

## Proposition

```
$roles = [
            'admin' => ['post-create', 'post-edit', 'post-delete', 'post-update'],
            'user' => ['user-create', 'user-edit', 'user-delete', 'user-update'],
        ];
```

## If Accepted

If accepted I would make the needed changes and send in a Pull Request.

## Additional Thoughts on seeding.

The Seeding Table shouldn't be a mandator part of `php artisan erag:publish-permission`, this should be made optional with a `--seed` option or published as a DatabaseSeeding file.

**Comment by herovish143** [comment]
Thank you for your input! Your changes are accepted. Please go ahead with the modifications and submit a Pull Request.

Additional Thoughts on seeding.
Thank you for your suggestions! I completely agree with your proposition regarding the seeding table. It shouldn’t be a mandatory part of the php artisan erag:publish-permission command. Instead, we should make it optional by adding a --seed option or allowing it to be published as a separate DatabaseSeeding file.

This way, users can choose to publish the seeder if they want to include it in their setup.

Looking forward to your modifications and the Pull Request!

**Comment by eramitgupta** [comment]
Thank you both for your valuable input and collaboration!

@Houbsi, I appreciate your proposal on standardizing the permission names to follow the format {{model}}-{{action}}. This definitely makes sense, as it enhances the consistency and clarity of the permissions. Let's proceed with this change.

Regarding the seeder, I agree with the idea of making it optional. Allowing users to include the seeder with a --seed option or publishing it separately ensures flexibility and better customization. I will review the changes as soon as you submit the Pull Request.

Thanks again for your contributions. Looking forward to working with you to improve the package!

**Comment by eramitgupta** [comment]
@Houbsi 

{{model}}-{{action}} Are you working on this feature?

**Comment by Houbsi** [comment]
Yes, sorry I'm on nightshift duty atm. I had the weekend planned for it.

**Comment by eramitgupta** [comment]
Hi mate @Houbsi,  
Can you fix? The closing single quote is missing in `'user-create'`.

**Comment by Houbsi** [comment]
done after the PR was merged
